# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0002_auto_20190110_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('num', models.IntegerField()),
            ],
        ),
    ]
