# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0003_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=255)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dr.Goods')),
            ],
        ),
    ]
