# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-12 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0004_allimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='user',
            field=models.ManyToManyField(to='dr.User'),
        ),
        migrations.AlterField(
            model_name='allimg',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dr.Goods'),
        ),
    ]
