# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0008_auto_20190114_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allimg',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dr.Goods'),
        ),
    ]
