# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dr', '0011_auto_20190115_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dr.Goodslist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dr.User')),
            ],
        ),
        migrations.AlterField(
            model_name='allimg',
            name='goods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dr.Goods'),
        ),
    ]
